### ISSUE TITLE
Error in creating a folder from OME-TIFF files Nanostring

### ISSUE THREAD

**Issue by ClaudiaZagami** [bioturing/pyBCS#49]
Hello, I am experiencing an error when trying to create a folder from OME-TIFF files for Nanostring. 
here the error: 
PS C:\Users\claud> & C:/Users/claud/AppData/Local/Microsoft/WindowsApps/python3.10.exe "c:/Users/claud/Dropbox (Ludwig Institute for Cancer Research)/Nanostring_data/convertOME.py"C:\Users\claud\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default  warn("Workbook contains no default style, apply openpyxl's default")Loading ROIs from 27C_WTA_02.ome.tiff ...
Traceback (most recent call last):
  File "c:\Users\claud\Dropbox (Ludwig Institute for Cancer Research)\Nanostring_data\convertOME.py", line 2, in <module>    ome = OME('C:/Users/claud/Dropbox (Ludwig Institute for Cancer Research)/Nanostring_data/filtering_normalisation/CZ1_filtered targets_normalised.xlsx', 'C:/Users/claud/Dropbox (Ludwig Institute for Cancer Research)/Nanostring_data/OME-TIFF')  File "C:\Users\claud\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyBCS\dsp.py", line 30, in __init__
    roi, tif = self.extract_ome_tiff(ome_dir)  File "C:\Users\claud\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyBCS\dsp.py", line 128, in extract_ome_tiff
    [roi_info.append(get_mask(m)) for m in mask]  File "C:\Users\claud\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyBCS\dsp.py", line 128, in <listcomp>
    [roi_info.append(get_mask(m)) for m in mask]
  File "C:\Users\claud\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyBCS\dsp.py", line 118, in get_mask
    "SegmentLabel": mask["@Text"],KeyError: '@Text'

It looks like "@Text" isn't contained in the mask variable which is causing the error, but I'm not sure why.

**Comment by ClaudiaZagami** [comment]
Hello, may I have assistance on this issue, please? thanks
